id: P003249
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:50:16.477781
source_metadata:
  id: bdr:W3CN5270
  title: དགའ་ལྡན་ཐོས་བསམ་དར་རྒྱས་གླིང་གི་གནས་ཡིག་དད་པའི་ས་བོན།
  author: ''
  volumes:
    a5755de7a4bb4584ae74d819368c5c9a:
      image_group_id: I3CN5272
      title: ''
      volume_number: 1
      total_pages: 151
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
